modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Wagers-of-Industrial-Warfare/OgdenMod/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Wagers-of-Industrial-Warfare/OgdenMod"
logoFile="icon.png"
credits="Programmed by rbasamoyai"
authors="${mod_authors}"

#displayTest="MATCH_VERSION"

description="""A firearms engine for Minecraft."""

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
